version: '3'

services:
  node:
    image: node:14.13.1
    working_dir: '/var/www'
    volumes:
      - './:/var/www'
    ports:
      - '4000:4000'
    links:
      - mongo
    environment:
      - URL_MONGO=mongodb://api:b00ker@mongo
    command: npm run serve
    
  mongo:
    image: mongo:4
    volumes:
      - './mongo/data:/data/db'
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=api
      - MONGO_INITDB_ROOT_PASSWORD=b00ker
